// Generated by CoffeeScript 1.7.1
(function() {
  var moment, userFactory;

  userFactory = function(user) {
    moment;
    var getInfo;
    getInfo = function() {
      var timer;
      if (user.getZombie) {
        user.timer = moment(user.lastActionDate).add(24, 'hours').diff(moment());
        user.isDead = user.timer < 0;
        user.role = 'zombie';
      } else {
        timer = moment(user.lastActionDate).add(30, 'hours').diff(moment());
        if (timer > 0) {
          user.timer = timer;
          user.role = 'human';
          user.isDead = false;
        } else {
          user.role = 'zombie';
          user.timer = moment(user.lastActionDate).add(54, 'hours').diff(moment());
          user.isDead = user.timer < 0;
        }
      }
      user.lastActionDateFormat = moment(user.lastActionDate).format("YYYY-MM-DD HH:mm");
      user.getZombieFormat = moment(user.lastActionDate).format("YYYY-MM-DD HH:mm");
      return user;
    };
    return {
      getInfo: getInfo
    };
  };

  if (module && module.exports) {
    moment = require('moment');
    return module.exports = userFactory;
  } else {
    window.userFactory = userFactory;
  }

}).call(this);

//# sourceMappingURL=userFactory.map
