// Generated by CoffeeScript 1.7.1
(function() {
  var config, moment, userFactory;

  moment = require('moment');

  config = require('cnf');

  userFactory = function(user) {
    moment;
    var getInfo;
    getInfo = function() {
      var hasStarted, start, timer;
      if (user.getZombie || user.selfZombie) {
        user.timer = moment(user.lastActionDate).add(30, 'hours').diff(moment());
        user.isDead = user.timer < 0;
        user.role = 'zombie';
      } else {
        start = moment(config.startDate, "YYYY-MM-DD HH-mm Z");
        hasStarted = start.diff(moment()) < 0;
        if (hasStarted) {
          timer = moment(user.lastActionDate).add(30, 'hours').diff(moment());
          if (moment(user.lastActionDate).diff(start) < 0) {
            timer = moment(start).add(30, 'hours').diff(moment());
          }
        } else {
          timer = moment.duration(30, 'hours').asMilliseconds();
        }
        if (timer > 0) {
          user.timer = timer;
          user.role = 'human';
          user.isDead = false;
        } else {
          user.role = 'zombie';
          user.timer = moment(user.lastActionDate).add(60, 'hours').diff(moment());
          user.isDead = user.timer < 0;
        }
      }
      if (user.isDead) {
        user.role = 'dead';
      }
      return user;
    };
    return {
      getInfo: getInfo
    };
  };

  module.exports = userFactory;

}).call(this);

//# sourceMappingURL=userFactory.map
