// Generated by CoffeeScript 1.7.1
(function() {
  var moment, userFactory;

  userFactory = function(user) {
    moment;
    var isOut, izZombie;
    izZombie = function() {
      if (user.getZombie) {
        return true;
      } else {
        return moment().subtract(moment(user.lastActionDate)).subtract(1, 'days') < 0;
      }
    };
    isOut = function() {
      if (user.getZombie) {
        return moment().subtract(moment(user.lastActionDate)).subtract(1, 'days') < 0;
      } else {
        return moment().subtract(moment(user.lastActionDate)).subtract(2, 'days') < 0;
      }
    };
    return {
      izZombie: izZombie,
      izOut: isOut
    };
  };

  if (userFactory && userFactory.exports) {
    moment = require('moment');
    return userFactory.exports = userFactory;
  } else {
    moment = window.moment;
    window.userFactory = userFactory;
  }

}).call(this);

//# sourceMappingURL=userFactory.map
