// Generated by CoffeeScript 1.7.1
(function() {
  var VKontakteStrategy, app, bodyParser, cookieParser, ensureAuthenticated, express, expressSession, http, passport, port, server, vkAppId;

  express = require('express');

  http = require('http');

  passport = require('passport');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  expressSession = require('express-session');

  VKontakteStrategy = require('passport-vkontakte').Strategy;

  vkAppId = process.env.HVZ_VK_APP_ID || 4334105;

  app = express();

  server = http.createServer(app);

  app.set('views', __dirname + '/views');

  app.set('view engine', 'jade');

  app.use(express["static"](__dirname + '/client'));

  app.use(cookieParser(process.env.HVZ_COOKIE_SECRET || 'this is super duper secret string'));

  app.use(bodyParser());

  app.use(expressSession({
    secret: process.env.HVZ_SESSION_SECRET || 'keyboard cat'
  }));

  app.use(passport.initialize());

  app.use(passport.session());

  app.get('/', function(req, res) {
    return res.send('hello world');
  });

  app.get('/auth/vkontakte', passport.authenticate('vkontakte'), function(req, res) {
    return res.end('LOOOL');
  });

  app.get('/auth/vkontakte/callback', passport.authenticate('vkontakte', {
    failureRedirect: '/login'
  }));

  (function(req, res) {
    return res.redirect('/');
  });

  app.get('/login', function(req, res) {
    return res.render('login');
  });

  passport.use(new VKontakteStrategy({
    clientID: vkAppId,
    clientSecret: process.env.HVZ_VK_SECRET,
    callbackURL: "http://localhost:5000/auth/vkontakte/callback"
  }, function(accessToken, refreshToken, profile, done) {
    console.log('User.findOrCreate', accessToken, refreshToken, profile);
    return done();
  }));

  ensureAuthenticated = function(req, res, next) {
    if (req.isAuthenticated()) {
      return next();
    } else {
      return res.redirect('/login');
    }
  };

  port = process.env.PORT || 5000;

  server.listen(port);

}).call(this);

//# sourceMappingURL=app.map
