// Generated by CoffeeScript 1.7.1
(function() {
  $.cookie('mobile', true, {
    path: '/'
  });

  $(function() {
    return $('#desktopVersion').on("click touchend", function() {
      $.removeCookie('mobile', {
        path: '/'
      });
      return window.location.href = '/';
    });
  });

}).call(this);

//# sourceMappingURL=mobile.map
