// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var timer;
    timer = $('.timer').FlipClock({
      countdown: true,
      autoStart: false
    });
    timer.setTime($('.timer').data('timer') / 1000);
    return timer.start();
  });

}).call(this);

//# sourceMappingURL=profile.map
