// Generated by CoffeeScript 1.7.1
(function() {
  var UserFactory, moment;

  UserFactory = require('../modules/userFactory');

  moment = require('moment');

  module.exports = function(role) {
    return function(req, res, next) {
      var isAuth, user, userRole, _ref;
      res.viewData = res.viewData || {};
      res.viewData.moment = moment;
      res.viewData.formatDate = function(date) {
        return moment(date).format('YYYY-MM-DD HH:mm:ss');
      };
      isAuth = req.isAuthenticated();
      res.viewData.isAuth = isAuth;
      user = req.user || {};
      user.isAdmin = isAuth && req.user.role === 'admin';
      if (isAuth) {
        UserFactory(user).getInfo();
      }
      userRole = (_ref = req.user) != null ? _ref.role : void 0;
      res.viewData.user = user;
      if (isAuth && role === 'any') {
        return next();
      }
      if (user.isAdmin || role === void 0) {
        return next();
      }
      if (userRole !== role) {
        return res.redirect('/');
      }
      return next();
    };
  };

}).call(this);

//# sourceMappingURL=authorizeRole.map
