// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(role) {
    return function(req, res, next) {
      var userRole, _ref;
      userRole = (_ref = req.user) != null ? _ref.role : void 0;
      res.viewData = res.viewData || {};
      res.viewData.isAuth = req.isAuthenticated();
      res.viewData.user = req.user;
      if (userRole === 'admin' || role === void 0) {
        return next();
      }
      if (userRole !== role) {
        return res.redirect('/');
      }
      return next();
    };
  };

}).call(this);

//# sourceMappingURL=authorizeRole.map
