// Generated by CoffeeScript 1.7.1
(function() {
  var config, log, mongoConnectionString, mongoose, requireTree;

  mongoose = require('mongoose');

  requireTree = require('require-tree');

  config = require('cnf');

  mongoConnectionString = config.mongo;

  log = require('winston-wrapper')(module);

  requireTree('../../models/');

  module.exports = function(done) {
    var db, e;
    db = mongoose.connection;
    db.on('error', function(err) {
      console.error('connection error:' + err);
      return done(err);
    });
    db.once('open', function() {
      console.info('successfully connected to db'.green);
      return done();
    });
    try {
      mongoose.connect(mongoConnectionString);
      return log.info('Started connection on ' + mongoConnectionString.cyan + ', waiting for it to open...'.grey);
    } catch (_error) {
      e = _error;
      return log.error(('Setting up failed to connect to ' + mongoConnectionString).red, err.message);
    }
  };

}).call(this);

//# sourceMappingURL=01_mongoose.map
