// Generated by CoffeeScript 1.7.1
(function() {
  var Medicine, mongoose;

  mongoose = require('mongoose');

  Medicine = new mongoose.Schema({
    code: {
      type: String,
      required: true,
      unique: true
    },
    generated: {
      type: Date,
      required: true
    },
    usedBy: {
      type: String
    },
    usedTime: {
      type: Date
    }
  });

  mongoose.model('medicine', Medicine);

}).call(this);

//# sourceMappingURL=medicine.map
