// Generated by CoffeeScript 1.7.1
(function() {
  var UserSchema, mongoose;

  mongoose = require('mongoose');

  UserSchema = new mongoose.Schema({
    vkontakteId: {
      type: String,
      required: true,
      unique: true
    },
    profile: {
      type: Object
    }
  });

  mongoose.model('user', UserSchema);

}).call(this);

//# sourceMappingURL=user.map
