// Generated by CoffeeScript 1.7.1
(function() {
  var UserSchema, mongoose;

  mongoose = require('mongoose');

  UserSchema = new mongoose.Schema({
    vkontakteId: {
      type: String,
      required: true,
      unique: true
    },
    profile: {
      type: Object
    },
    role: {
      type: String
    },
    lastActionDate: {
      type: Date
    },
    registered: {
      type: Date
    },
    getZombie: {
      type: Date
    },
    hash: {
      type: String
    }
  });

  mongoose.model('user', UserSchema);

}).call(this);

//# sourceMappingURL=user.map
